export type IntegrationConfigType = {
  id: number;
  projectId: number;
  service: string;
  apiKey: string;
  settings: Record<string, string> | null;
  createdAt: string;
  updatedAt: string;
};

export type IntegrationsMessages = {
  integrations: string;
  aiProviders: string;
  anthropic: string;
  anthropicDescription: string;
  apiKey: string;
  apiKeyPlaceholder: string;
  saveKey: string;
  saving: string;
  deleteKey: string;
  noIntegrations: string;
  successSaved: string;
  errorSaved: string;
  successDeleted: string;
  errorDeleted: string;
  connected: string;
  notConfigured: string;
  close: string;
  delete: string;
  areYouSure: string;
  edit: string;
  cancel: string;
  gitProviders: string;
  github: string;
  githubDescription: string;
  gitlab: string;
  gitlabDescription: string;
  token: string;
  githubTokenPlaceholder: string;
  gitlabTokenPlaceholder: string;
  instanceUrl: string;
  namespace: string;
  namespacePlaceholder: string;
  // Project connections
  projectConnections: string;
  sourceProject: string;
  testProject: string;
  connectProviderFirst: string;
  branch: string;
  branchPlaceholder: string;
  autoAnalyzeCommits: string;
  saveSourceProject: string;
  saveTestProject: string;
  sourceProjectSaved: string;
  sourceProjectSaveError: string;
  testProjectSaved: string;
  testProjectSaveError: string;
  automationTool: string;
  automationLanguage: string;
  notSet: string;
  pickRepoTitle: string;
  searchReposPlaceholder: string;
  loadingRepos: string;
  noReposFound: string;
  browse: string;
  toolPlaywright: string;
  toolCypress: string;
  toolPytest: string;
  langTypescript: string;
  langJavascript: string;
  langPython: string;
  configureSourceProject: string;
  configureTestProject: string;
  sourceProjectRemoved: string;
  testProjectRemoved: string;
};
