export type IntegrationConfigType = {
  id: number;
  projectId: number;
  service: string;
  apiKey: string;
  settings: Record<string, string> | null;
  createdAt: string;
  updatedAt: string;
};

export type IntegrationsMessages = {
  integrations: string;
  aiProviders: string;
  anthropic: string;
  anthropicDescription: string;
  apiKey: string;
  apiKeyPlaceholder: string;
  saveKey: string;
  saving: string;
  deleteKey: string;
  noIntegrations: string;
  successSaved: string;
  errorSaved: string;
  successDeleted: string;
  errorDeleted: string;
  connected: string;
  notConfigured: string;
  close: string;
  delete: string;
  areYouSure: string;
  edit: string;
  cancel: string;
  gitProviders: string;
  github: string;
  githubDescription: string;
  gitlab: string;
  gitlabDescription: string;
  token: string;
  githubTokenPlaceholder: string;
  gitlabTokenPlaceholder: string;
  instanceUrl: string;
  namespace: string;
  namespacePlaceholder: string;
};
