version: 2
updates:
  # root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  # docs
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    target-branch: "develop"
